### ISSUE TITLE
Get selected position

### ISSUE THREAD

**Issue by ckpenep** [alanvan0502/segmented-control-group#1]
Hello. How can I get selected button position ?

**Comment by alanvan0502** [comment]
@ckpenep You can set a callback on the `segmentedControlGroup`
`val segmentedControlGroup = findViewById<SegmentedControlGroup>(R.id.segmented_control_group)
  segmentedControlGroup.setOnSelectedOptionChangeCallback {
        Toast.makeText(context, "Button ${it + 1} selected", Toast.LENGTH_SHORT).show()
}`
Check out the `example` folder.
